# Found here: https://tomasfarias.dev/posts/sphinx-docs-with-poetry-and-github-pages/

name: Docs2Pages
on:
  push:
    # tags: '*'
    branches:
      - main
  # pull_request:
  #  branches:
  #    - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
      with:
        python-version: 3.10.2
    - uses: abatilo/actions-poetry@v2.1.4
    - name: install
      run: poetry install
    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd doc/
        poetry run sphinx-build -b html . _build
        cp -r _build/* ../gh-pages/
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages
